name: Production Deployment

on:
  push:
    branches: [ main ] # Only deploys when main is updated

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Client
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: yourdockerhub/client:latest

      # Repeat for 'admin' and 'server' folders...

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/user/my-monorepo
            docker compose pull
            docker compose up -d
            docker image prune -f # Cleanup old images